### PR TITLE
Fix unitless zero values

### LINKED ISSUE #7: unitless zero value bug
Hi :)

I'm using postcss and have following expression:

``` css
div {
    width: calc(100% - $width - $margin);
}
```

and I found strange behavior when try to use zero values:

``` css
// $width: 200px;
// $margin: 0; or $margin: 0px; or $margin: 0px;
// output: 
div {
    width: calc(100% - 200px - 0); // this is not valid expression inside 'calc' and browsers don't calculate it
}
```

but these are valid expressions:

``` css
width: calc(100% - 200px - 0px);
width: calc(100% - 200px - 0%);
```

so my question is: Could you fix this? Or this is a normal behavior?
thank you :)

### PR DESCRIPTION
**Pull request by dennisfrank**
This fixes #7 and should be also related to https://github.com/postcss/postcss-calc/issues/28.

### CODE REVIEW

**Comment by MoOx** [comment]
This might be considered as a breaking change, which annoys me. Maybe this should not be the default?
Can't you fix the sass mixins instead? Cause it's weird to deoptimize this reducer.

**Comment by dennisfrank** [comment]
Hm. But zero values without a value are breaking `calc()`. Browsers don't calculate it at all.

Check out this simplified example:

http://jsbin.com/punivivipo/edit?html,css,output

**Comment by MoOx** [comment]
Another WTF CSS :'(.
So will merge and release as a patch.

**Comment by dennisfrank** [comment]
Yeah. It makes no sense. :(

**Comment by MoOx** [comment]
Released as 1.2.4

**Comment by Dylan-Chapman** [comment]
So, what can be done about scenarios where we have something like `width: calc(99.99% * 1/1 - 0rem);` that can be reduced? This change breaks it from reducing down to simply `width: 99.99%`. I'd change the output manually if I could, but this is resulting code from Lost grid.

**Comment by MoOx** [comment]
What about fixing the code generated by Lost grid?

**Pull request merged**
