### PR TITLE
wrong rounding.

### PR DESCRIPTION
**Pull request by Scrum**
I added example showing wrong rounding.

### CODE REVIEW

**Comment by MoOx** [comment]
Well, it's a JavaScript problem? Not sure how to fix that.

**Comment by Scrum** [comment]
This not js problem.
This package will produce rounding in the intermediate calculations, instead of rounding the result.
Need to round off the final result of the computation.

Example:

``` console
*step: 1
(100/12) = 8.333333333333334 (pkg return 8.333)
(100*2) = 200

*step: 2
8.333*2 = 16.666
200/12 = 16.666666666666668

*step: 3 (round, 3)
result: Math.round(16.666 * 1000) / 1000 => 16.666
result: Math.round(16.666666666666668 * 1000) / 1000 => 16.667
```

**Comment by MoOx** [comment]
The problem is own this function works: it will reduce when possible, so for now it producing rounding for each calculations. If you have a better algorithm to fix this, PR is welcome :)

**Comment by Scrum** [comment]
@MoOx Fixed

**Comment by Scrum** [comment]
Ping!

**Comment by MoOx** [comment]
Released as 1.2.3

**Comment by Scrum** [comment]
Thanks.

**Pull request merged**
