### PR TITLE
jison: switch to maintained fork

### PR DESCRIPTION
**Pull request by davidgovea**
Hi @MoOx, thanks for this library!

I see that you're already using a custom fork of jison -- we are having issues downstream due to the `main()` function added to the end of `parser.js` by jison (for command-line usability -- it `require()`s the `fs` module, which doesn't exist in our build environment).

There are quite a few dangling PRs in the main jison repo, but this one is pretty active & maintained:
https://github.com/GerHobbelt/jison
available on npm: https://www.npmjs.com/package/jison-gho

I was considering creating my own fork, but I'd rather go with the community if possible.

Looks like the tests are all still passing -- hopefully this fork also addresses the use-cases that lead to you going off-package as well.

### CODE REVIEW

**Comment by MoOx** [comment]
Could this be released as a patch? Or should this be a breaking change?

**Comment by davidgovea** [comment]
Hi @MoOx -

This should not affect users at all. Tests are passing -- patch should be fine.
Thanks for replying!

**Comment by TVke** [comment]
@MoOx 

Any news on merging and releasing this patch?

**Review by MoOx — APPROVED** [review]

**Comment by MoOx** [comment]
2.1.7 is out

**Pull request merged**
